# Generated by Plotly Studio
# Updated with professional, accessible theme

theme = {
    # Primary accent colors - professional and accessible
    "accent":"#5470C6",
    "accent_positive":"#52B44B",
    "accent_negative":"#EE6666",
    
    # Background colors - clean white
    "background_content":"#FFFFFF",
    "background_page":"#FFFFFF",
    "body_text":"#2C3E50",
    
    # Borders - thin and light gray
    "border":"#E5E5E5",
    "border_style":{
        "name":"solid",
        "borderWidth":"1px",
        "borderStyle":"solid",
        "borderRadius":4
    },
    
    # Button styling
    "button_border":{
        "width":"1px",
        "color":"#E5E5E5",
        "radius":"4px"
    },
    "button_capitalization":"none",
    "button_text":"#FFFFFF",
    "button_background_color":"#5470C6",
    
    # Control styling
    "control_border":{
        "width":"1px",
        "color":"#E5E5E5",
        "radius":"4px"
    },    "control_background_color":"#FFFFFF",
    "control_text":"#2C3E50",
    
    # Card styling - subtle shadows and thin borders
    "card_margin":"20px",
    "card_padding":"16px",
    "card_border":{
        "width":"1px",
        "style":"solid",
        "color":"#E5E5E5",
        "radius":"4px"
    },
    "card_background_color":"#FFFFFF",
    "card_box_shadow":"0px 4px 6px rgba(0, 0, 0, 0.05)",
    "card_outline":{
        "width":"1px",
        "style":"solid",
        "color":"#E5E5E5"
    },
    
    # Card header styling
    "card_header_accent":"#5470C6",
    "card_header_margin":"0px 0px 16px 0px",
    "card_header_padding":"12px",
    "card_header_border":{
        "width":"0px 0px 1px 0px",
        "style":"solid",
        "color":"#E5E5E5",
        "radius":"0px"
    },    "card_header_background_color":"#FFFFFF",
    "card_title_text":"#1A365D",
    "card_title_font_size":"20px",
    "card_description_background_color":"#FFFFFF",
    "card_description_text":"#4A5568",
    "card_description_font_size":"14px",
    "card_menu_background_color":"#FFFFFF",
    "card_menu_text":"#2C3E50",
    "card_header_box_shadow":"none",
    "card_accent":"#5470C6",
    
    # Responsive breakpoints
    "breakpoint_font":"700px",
    "breakpoint_stack_blocks":"700px",
    
    # Multi-hued categorical color palette - balanced and distinguishable
    "colorway":[
        "#5470c6",
        "#91cc75",
        "#fac858",
        "#ee6666",
        "#73c0de",
        "#3ba272",
        "#fc8452",
        "#9a60b4",
        "#ea7ccc"
    ],    
    # Perceptually uniform sequential color scale
    "colorscale":[
        "#F7F7F7",
        "#E8E9F3",
        "#D9DBE9",
        "#C9CDDF",
        "#B9BFD5",
        "#A9B1CB",
        "#99A3C1",
        "#8995B7",
        "#7987AD",
        "#6979A3",
        "#5A6B99",
        "#5470C6"
    ],
    
    # Bootstrap component colors
    "dbc_primary":"#5470C6",
    "dbc_secondary":"#6C757D",
    "dbc_info":"#73c0de",
    "dbc_gray":"#6C757D",
    "dbc_success":"#52B44B",
    "dbc_warning":"#fac858",
    "dbc_danger":"#EE6666",
    
    # Typography - clean and legible
    "font_family":"Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
    "font_family_header":"Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
    "font_family_headings":"Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",    "font_size":"14px",
    "font_size_smaller_screen":"14px",
    "font_size_header":"24px",
    
    # Footer styling
    "footer_background_color":"#FFFFFF",
    "footer_title_text":"#2C3E50",
    "footer_title_font_size":"20px",
    "title_capitalization":"none",
    
    # Header styling
    "header_content_alignment":"spread",
    "header_margin":"0px 0px 24px 0px",
    "header_padding":"16px",
    "header_border":{
        "width":"0px 0px 1px 0px",
        "style":"solid",
        "color":"#E5E5E5",
        "radius":"0px"
    },
    "header_background_color":"#FFFFFF",
    "header_box_shadow":"none",
    "header_text":"#1A365D",
    "heading_text":"#1A365D",
    
    # Hero section styling
    "hero_background_color":"#FFFFFF",
    "hero_title_text":"#1A365D",
    "hero_title_font_size":"36px",
    "hero_subtitle_text":"#4A5568",
    "hero_subtitle_font_size":"16px",    "hero_controls_background_color":"#FFFFFF",
    "hero_controls_label_text":"#2C3E50",
    "hero_controls_label_font_size":"14px",
    "hero_controls_grid_columns":4,
    "hero_controls_accent":"#5470C6",
    "hero_border":{
        "width":"0",
        "style":"solid",
        "color":"transparent"
    },
    "hero_padding":"24px",
    "hero_gap":"24px",
    
    # Text colors
    "text":"#2C3E50",
    
    # Report styling
    "report_background":"#FFFFFF",
    "report_background_content":"#FFFFFF",
    "report_background_page":"#FFFFFF",
    "report_text":"#2C3E50",
    "report_font_family":"Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
    "report_font_size":"14px",
    
    # Section styling
    "section_padding":"24px",
    "section_title_font_size":"24px",
    "section_gap":"24px",
    "report_border":"#E5E5E5",    
    # Graph gridlines - very subtle light gray
    "graph_grid_color":"#EEEEEE",
    
    # Table formatting - no zebra striping, clean white rows
    "table_striped_even":"#FFFFFF",
    "table_striped_odd":"#FFFFFF",
    "table_border":"#E5E5E5",
    "table_row_separator":"#F0F0F0",
    
    # Tag styling
    "tag_background_color":"#F7F7F7",
    "tag_text":"#2C3E50",
    "tag_font_size":"12px",
    "tag_border":{
        "width":"1px",
        "style":"solid",
        "color":"#E5E5E5",
        "radius":"4px"
    },
    
    # Tooltip styling
    "tooltip_background_color":"#2C3E50",
    "tooltip_text":"#FFFFFF",
    "tooltip_font_size":"12px",
    
    # Control panel styling
    "top_control_panel_border":{
        "width":"1px",
        "style":"solid",
        "color":"#E5E5E5"
    },
    
    # Overall color scheme
    "color_scheme":"light",
    "header_controls_background_color":"#FFFFFF"
}